language: cpp
os:
  - linux
  - osx
compiler:
  - gcc
matrix:
  allow_failures:
    - os: osx
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      CFLAGS="-I/usr/local/opt/openssl/include $CFLAGS";
      LDFLAGS="-L/usr/local/opt/openssl/lib $LDFLAGS";
    fi
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  make all
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
